# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 412fc79e0caf6ea782a074fbeaffbf4f7e2d018b2f91ac3b05e7d2cb5ca5451a530ec340fc1313c74a143c8ff2bdd50f0ca89e4a340d41cbaf252ab2df3e72a8

test:
  secret_key_base: ba7f26a6afb805f74a66d79f676a0e43e528880f94de6e6fe0a6d7501d30f0d030fd45e368b7656ffdb64cb8655b5b2c2be70fa97fbe629dcd2820a07ccd07be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
